/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as RecentRouteImport } from './routes/recent'
import { Route as AlgorithmsIndexRouteImport } from './routes/algorithms/index'
import { Route as AlgorithmsCategoryIndexRouteImport } from './routes/algorithms/$category/index'
import { Route as AlgorithmsCategoryAlgorithmRouteImport } from './routes/algorithms/$category/$algorithm'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentRoute = RecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmsIndexRoute = AlgorithmsIndexRouteImport.update({
  id: '/algorithms/',
  path: '/algorithms/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmsCategoryIndexRoute = AlgorithmsCategoryIndexRouteImport.update({
  id: '/algorithms/$category/',
  path: '/algorithms/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmsCategoryAlgorithmRoute =
  AlgorithmsCategoryAlgorithmRouteImport.update({
    id: '/algorithms/$category/$algorithm',
    path: '/algorithms/$category/$algorithm',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/recent': typeof RecentRoute
  '/algorithms/': typeof AlgorithmsIndexRoute
  '/algorithms/$category/$algorithm': typeof AlgorithmsCategoryAlgorithmRoute
  '/algorithms/$category/': typeof AlgorithmsCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/recent': typeof RecentRoute
  '/algorithms': typeof AlgorithmsIndexRoute
  '/algorithms/$category/$algorithm': typeof AlgorithmsCategoryAlgorithmRoute
  '/algorithms/$category': typeof AlgorithmsCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/recent': typeof RecentRoute
  '/algorithms/': typeof AlgorithmsIndexRoute
  '/algorithms/$category/$algorithm': typeof AlgorithmsCategoryAlgorithmRoute
  '/algorithms/$category/': typeof AlgorithmsCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favorites'
    | '/recent'
    | '/algorithms/'
    | '/algorithms/$category/$algorithm'
    | '/algorithms/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favorites'
    | '/recent'
    | '/algorithms'
    | '/algorithms/$category/$algorithm'
    | '/algorithms/$category'
  id:
    | '__root__'
    | '/'
    | '/favorites'
    | '/recent'
    | '/algorithms/'
    | '/algorithms/$category/$algorithm'
    | '/algorithms/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritesRoute: typeof FavoritesRoute
  RecentRoute: typeof RecentRoute
  AlgorithmsIndexRoute: typeof AlgorithmsIndexRoute
  AlgorithmsCategoryAlgorithmRoute: typeof AlgorithmsCategoryAlgorithmRoute
  AlgorithmsCategoryIndexRoute: typeof AlgorithmsCategoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent': {
      id: '/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof RecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algorithms/': {
      id: '/algorithms/'
      path: '/algorithms'
      fullPath: '/algorithms/'
      preLoaderRoute: typeof AlgorithmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algorithms/$category/': {
      id: '/algorithms/$category/'
      path: '/algorithms/$category'
      fullPath: '/algorithms/$category/'
      preLoaderRoute: typeof AlgorithmsCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algorithms/$category/$algorithm': {
      id: '/algorithms/$category/$algorithm'
      path: '/algorithms/$category/$algorithm'
      fullPath: '/algorithms/$category/$algorithm'
      preLoaderRoute: typeof AlgorithmsCategoryAlgorithmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRoute: FavoritesRoute,
  RecentRoute: RecentRoute,
  AlgorithmsIndexRoute: AlgorithmsIndexRoute,
  AlgorithmsCategoryAlgorithmRoute: AlgorithmsCategoryAlgorithmRoute,
  AlgorithmsCategoryIndexRoute: AlgorithmsCategoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
